//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actor
    {
        public actor()
        {
            this.videoactors = new HashSet<videoactor>();
        }
        public int id { get; set; }
        public string name { get; set; }
        public virtual ICollection<videoactor> videoactors { get; set; }
    }
}
