//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advertiser
    {
        public advertiser()
        {
            this.banners = new HashSet<banner>();
            this.teasers = new HashSet<teaser>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string img_url { get; set; }
    
        public virtual ICollection<banner> banners { get; set; }
        public virtual ICollection<teaser> teasers { get; set; }
    }
}
