//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnetuser
    {
        public aspnetuser()
        {
            this.likes = new HashSet<like>();
            this.overviews = new HashSet<overview>();
            this.aspnetroles = new HashSet<aspnetrole>();
            this.episodehistories = new HashSet<episodehistory>();
            this.usermovies = new HashSet<usermovy>();
            this.userseasons = new HashSet<userseason>();
<<<<<<< HEAD
            this.subscriptions = new HashSet<subscription>();
            this.aspnetroles = new HashSet<aspnetrole>();
            this.statistics_banner = new HashSet<statistics_banner>();
            this.statistics_teaser = new HashSet<statistics_teaser>();
=======
            this.moviehistories = new HashSet<moviehistory>();
            this.statistics_banner = new HashSet<statistics_banner>();
            this.statistics_teaser = new HashSet<statistics_teaser>();
            this.subscriptions = new HashSet<subscription>();
            this.payments = new HashSet<payment>();
>>>>>>> faa7f4fc740b67c706f427a0b07b30fdf99fe2d1
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Discriminator { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> TariffId { get; set; }
    
<<<<<<< HEAD
        public virtual ICollection<aspnetuserclaim> aspnetuserclaims { get; set; }
        public virtual ICollection<aspnetuserlogin> aspnetuserlogins { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual ICollection<episodehistory> episodehistories { get; set; }
=======
>>>>>>> faa7f4fc740b67c706f427a0b07b30fdf99fe2d1
        public virtual ICollection<like> likes { get; set; }
        public virtual ICollection<overview> overviews { get; set; }
        public virtual ICollection<aspnetrole> aspnetroles { get; set; }
        public virtual ICollection<episodehistory> episodehistories { get; set; }
        public virtual ICollection<usermovy> usermovies { get; set; }
        public virtual ICollection<userseason> userseasons { get; set; }
<<<<<<< HEAD
        public virtual ICollection<subscription> subscriptions { get; set; }
        public virtual tariff tariff { get; set; }
        public virtual ICollection<aspnetrole> aspnetroles { get; set; }
        public virtual ICollection<statistics_banner> statistics_banner { get; set; }
        public virtual ICollection<statistics_teaser> statistics_teaser { get; set; }
=======
        public virtual ICollection<moviehistory> moviehistories { get; set; }
        public virtual ICollection<statistics_banner> statistics_banner { get; set; }
        public virtual ICollection<statistics_teaser> statistics_teaser { get; set; }
<<<<<<< HEAD
        public virtual ICollection<aspnetrole> aspnetroles { get; set; }
=======
        public virtual tariff tariff { get; set; }
        public virtual ICollection<subscription> subscriptions { get; set; }
        public virtual ICollection<payment> payments { get; set; }
>>>>>>> bb516119c725d7fd0811252f8325fa991635ad23
>>>>>>> faa7f4fc740b67c706f427a0b07b30fdf99fe2d1
    }
}
