//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class episode
    {
        public episode()
        {
            this.episodehistories = new HashSet<episodehistory>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public int season_id { get; set; }
    
        public virtual ICollection<episodehistory> episodehistories { get; set; }
        public virtual season season { get; set; }
    }
}
