//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public file()
        {
            this.histories = new HashSet<history>();
            this.purchases = new HashSet<purchase>();
        }
    
        public int id { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> video_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quality { get; set; }
        public Nullable<int> season_id { get; set; }
        public string title { get; set; }
        public Nullable<bool> trailer { get; set; }
        public Nullable<int> episode_number { get; set; }
    
        public virtual ICollection<history> histories { get; set; }
        public virtual ICollection<purchase> purchases { get; set; }
        public virtual season season { get; set; }
        public virtual video video { get; set; }
    }
}
