//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> file_id { get; set; }
        public Nullable<System.DateTime> watching_time { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual file file { get; set; }
    }
}
