//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class overview
    {
        public int id { get; set; }
        public string text { get; set; }
        public int video_id { get; set; }
        public string user_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public float rating { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual video video { get; set; }
    }
}
