//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int id { get; set; }
        public Nullable<int> video_id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<float> rating { get; set; }
        public string comment { get; set; }
    
        public virtual video video { get; set; }
        public virtual aspnetuser aspnetuser { get; set; }
    }
}
