//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class season
    {
        public season()
        {
            this.files = new HashSet<file>();
            this.userseasons = new HashSet<userseason>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<int> video_id { get; set; }
        public Nullable<int> season_number { get; set; }
    
        public virtual ICollection<file> files { get; set; }
        public virtual video video { get; set; }
        public virtual ICollection<userseason> userseasons { get; set; }
    }
}
