//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistics_teaser
    {
        public int id { get; set; }
        public Nullable<int> id_teasers { get; set; }
        public string id_users { get; set; }
        public Nullable<int> showAmount { get; set; }
        public Nullable<System.DateTime> dateShow { get; set; }
    
        public virtual teaser teaser { get; set; }
        public virtual aspnetuser aspnetuser { get; set; }
    }
}
