//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        public int id { get; set; }
        public Nullable<int> tariff_id { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public Nullable<int> payment_id { get; set; }
        public string UserId { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual payment payment { get; set; }
        public virtual tariff tariff { get; set; }
    }
}
