//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public video()
        {
            this.likes = new HashSet<like>();
            this.manufacturers = new HashSet<manufacturer>();
            this.movies = new HashSet<movy>();
            this.overviews = new HashSet<overview>();
            this.seasons = new HashSet<season>();
            this.trailers = new HashSet<trailer>();
            this.videoactors = new HashSet<videoactor>();
            this.videogenres = new HashSet<videogenre>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int age_limit { get; set; }
        public System.DateTime release_date { get; set; }
        public string details { get; set; }
        public string director { get; set; }
        public int type { get; set; }
        public string img_url { get; set; }
    
        public virtual ICollection<like> likes { get; set; }
        public virtual ICollection<manufacturer> manufacturers { get; set; }
        public virtual ICollection<movy> movies { get; set; }
        public virtual ICollection<overview> overviews { get; set; }
        public virtual ICollection<season> seasons { get; set; }
        public virtual ICollection<trailer> trailers { get; set; }
        public virtual ICollection<videoactor> videoactors { get; set; }
        public virtual ICollection<videogenre> videogenres { get; set; }
    }
}
