//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.manufacturers = new HashSet<manufacturer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<manufacturer> manufacturers { get; set; }
    }
}
