//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string secondname { get; set; }
        public string password { get; set; }
        public string login { get; set; }
        public int role_id { get; set; }
    
        public virtual role role { get; set; }
    }
}
