//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genre
    {
        public genre()
        {
            this.videogenres = new HashSet<videogenre>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<videogenre> videogenres { get; set; }
    }
}
