//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moviehistory
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int content_id { get; set; }
        public System.DateTime watching_date { get; set; }
        public float payment { get; set; }
    
        public virtual user user { get; set; }
        public virtual movie movy { get; set; }
    }
}
