//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMovie
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> movie_id { get; set; }
        public decimal payment { get; set; }
        public System.DateTime purchase_date { get; set; }
    
        public virtual user user { get; set; }
        public virtual movie movy { get; set; }
    }
}
