//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace CinemaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public video()
        {
            this.contents = new HashSet<content>();
            this.likes = new HashSet<like>();
            this.overviews = new HashSet<overview>();
            this.countries = new HashSet<country>();
            this.actors = new HashSet<actor>();
            this.genres = new HashSet<genre>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int age_limit { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime release_date { get; set; }
        [DataType(DataType.MultilineText)]
        public string details { get; set; }
        public string director { get; set; }
        public int type { get; set; }
        [DataType(DataType.ImageUrl)]
        public string img_url { get; set; }
    
        public virtual ICollection<content> contents { get; set; }
        public virtual ICollection<like> likes { get; set; }
        public virtual ICollection<overview> overviews { get; set; }
        public virtual ICollection<country> countries { get; set; }
        public virtual ICollection<actor> actors { get; set; }
        public virtual ICollection<genre> genres { get; set; }
    }
}
